SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY,
SUM((B.PRICE * S.SALES)) "TOTAL_SALES"
FROM BOOK B, AUTHOR A, BOOK_SALES S
WHERE S.SALES_DATE LIKE '2022-01-%'
AND B.BOOK_ID = S.BOOK_ID
AND B.AUTHOR_ID = A.AUTHOR_ID
GROUP BY 1, 3
ORDER BY 1 ASC,3 DESC;