SELECT p.PRODUCT_ID , p.PRODUCT_NAME , SUM(AMOUNT)*p.PRICE AS TOTAL_SALES
FROM FOOD_PRODUCT p, FOOD_ORDER o
WHERE o.PRODUCE_DATE LIKE "2022-05-%"
AND p.PRODUCT_ID = o.PRODUCT_ID
GROUP BY p.PRODUCT_ID, p.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;